### PR TITLE
Flatten directory structure

### PR DESCRIPTION
**Pull request by tarleb**

### CODE REVIEW

**Comment by arfon** [comment]
Hey @tarleb – sorry it took me ages to get to this. Is this PR good to merge as far as you're concerned (i.e., flattens all the folders etc.)

**Comment by tarleb** [comment]
I don't quite remember, but it's possible that the PR doesn't catch all
changes that were made to the directory structure, and that it might not
update some papers that were added after this PR was created, but before
the Inara changes were merged. So it's probably be better to close this
and create a new PR.

If you prefer to do the changes yourself, here's the script that I used.
(at least I *think* that's what I used 😬)

----

#!/bin/sh
set -e
find . -maxdepth 2 -name media -type d | \
while IFS= read -r media; do
    paper=$(basename ${media%/media*})
    printf 'Processing %s...\n' "$paper"
    find "$media" -type f | while IFS= read -r fullimgpath; do
        # original path relative to JATS file; remove prefix
        imgpath=${fullimgpath#*joss.?????/}
        # image filename
        img=$(basename "$fullimgpath")

        # Regex removing folders from image paths
        printf 'Replacing references to %s\n' "$imgpath"
        regexp="s#xlink:href=\"$imgpath\"#xlink:href=\"$img\"#g"
        sed -i'' -e "$regexp" "$paper"/10.21105."$paper".jats

        # Move image into base dir
        newpath="${paper}/${img}"
        printf 'Renaming %s to %s\n' "$fullimgpath" "$newpath"
        git mv "$fullimgpath" "$newpath"
    done

    printf 'Removing media folder %s\n' "$media"
    rmdir -r "$media"
done

**Comment by tarleb** [comment]
Re-posting the script via the web interface just to get proper syntax highlighting.

``` sh
#!/bin/sh
set -e
find . -maxdepth 2 -name media -type d | \
while IFS= read -r media; do
    paper=$(basename ${media%/media*})
    printf 'Processing %s...\n' "$paper"
    find "$media" -type f | while IFS= read -r fullimgpath; do
        # original path relative to JATS file; remove prefix
        imgpath=${fullimgpath#*joss.?????/}
        # image filename
        img=$(basename "$fullimgpath")

        # Regex removing folders from image paths
        printf 'Replacing references to %s\n' "$imgpath"
        regexp="s#xlink:href=\"$imgpath\"#xlink:href=\"$img\"#g"
        sed -i'' -e "$regexp" "$paper"/10.21105."$paper".jats

        # Move image into base dir
        newpath="${paper}/${img}"
        printf 'Renaming %s to %s\n' "$fullimgpath" "$newpath"
        git mv "$fullimgpath" "$newpath"
    done

    printf 'Removing media folder %s\n' "$media"
    rmdir -r "$media"
done
```

**Comment by tarleb** [comment]
Closing, new PR will follow

**Pull request closed without merging**
